/** Writes docs/lane-b/EVIDENCE_AUDIT.md: computed facts, evidence IDs, remedy basis and expected outcome per fixture. */
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildEvidence } from "../src/adapters/index.js";
import { formatSgd } from "../src/calc/money.js";
import { loadDataset } from "../src/node.js";
import { getRemedyBasis } from "../src/tools.js";

const pkg = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(pkg, "..", "..", "docs", "lane-b", "EVIDENCE_AUDIT.md");
const ds = loadDataset();
const esc = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const L: string[] = [
  "# Evidence and calculation audit",
  "",
  "> Generated by `npm run audit` in `packages/evidence`. Do not edit by hand.",
  "> All data is SYNTHETIC. Clauses are from the DEMONSTRATION POLICY (not Ryde policy).",
  "",
  `Policy: \`${ds.policy.policyId}\` v${ds.policy.version} — ${ds.policy.disclaimer}`,
  "",
  "## Summary",
  "",
  "| Fixture | Purpose | Category | Expected status | Favours | Remedy | Amount | Clauses |",
  "|---|---|---|---|---|---|---|---|",
];
for (const e of ds.expectedOutcomes) {
  L.push(`| ${e.fixtureId} | ${e.purpose} | ${e.category} | ${e.status} | ${e.favours ?? "—"} | ${e.remedyId ?? "—"} | ${e.amountCents === null ? "—" : `${e.amountCents} (${formatSgd(e.amountCents)})`} | ${e.clauseIds.join(", ")} |`);
}
for (const f of ds.fixtures) {
  const b = buildEvidence(f, ds.policy);
  const e = ds.expectedOutcomes.find((x) => x.fixtureId === f.fixtureId);
  L.push("", `## ${f.fixtureId} — ${f.label} (${f.purpose}, ${f.dispute.category})`, "");
  L.push(`Dispute \`${f.dispute.id}\`, trip \`${f.dispute.tripId}\`, filed ${f.dispute.filedAt}.`, "");
  L.push("### Evidence records", "", "| ID | Family | Kind | Summary |", "|---|---|---|---|");
  for (const r of b.records) L.push(`| \`${r.id}\` | ${r.family} | ${r.kind} | ${esc(r.summary)} |`);
  if (b.unavailable.length) {
    L.push("", "**Unavailable families:**", "");
    for (const u of b.unavailable) L.push(`- \`${u.family}\`: ${u.reason}`);
  }
  const key = b.records.filter((r) => ["route_metrics", "pickup_metrics", "rider_location", "contact_summary"].includes(r.kind));
  if (key.length) {
    L.push("", "### Computed facts", "");
    for (const r of key) L.push(`\`${r.id}\``, "", "```json", JSON.stringify(r.facts, null, 2), "```", "");
  }
  const fare = b.records.find((r) => r.id === "PAY-FARE");
  if (fare) L.push("", `**Fare check:** arithmeticValid = ${String(fare.facts.arithmeticValid)}; anomalies: ${JSON.stringify(fare.facts.arithmeticAnomalies)}; observations: \`${JSON.stringify(fare.facts.observations)}\``);
  L.push("", "### Remedy basis", "", "| Remedy | Eligible cents | Formula / reason |", "|---|---|---|");
  for (const r of getRemedyBasis(ds, f.dispute.id)) L.push(`| ${r.remedyId} | ${r.eligibleCents ?? "null"} | ${esc(r.eligibleCents === null ? `${r.unavailableReason} — ${r.formula}` : r.formula)} |`);
  if (e) {
    L.push("", "### Expected outcome", "");
    L.push(`- Status **${e.status}**, favours **${e.favours ?? "—"}**, remedy **${e.remedyId ?? "—"}**, amount **${e.amountCents ?? "—"}**`);
    L.push(`- Decisive evidence: ${e.decisiveEvidenceIds.map((x) => `\`${x}\``).join(", ") || "—"}; missing families: ${e.missingFamilies.join(", ") || "—"}`);
    L.push(`- Clauses: ${e.clauseIds.join(", ")}`, `- Rationale: ${e.rationale}`);
  }
}
L.push(
  "",
  "## Known discrepancy with the handoff reference values",
  "",
  "Handoff section 6.5 states an N3 driver wait of 210 s. Under the exact section 6.1 trace builder, the N3 approach",
  "ping 15 s before arrival is 146.7 m from the pickup pin (rounded 147 m, within the 150 m NS-1 limit), so",
  "`firstWithinThresholdTs` is A−15 and the spec-exact wait is **225 s**. `waitedMinimum` is false either way and the",
  "expected outcome (refund S$5.00) is unchanged. The implementation follows the exact rules; the discrepancy is",
  "recorded for the human owner to confirm.",
  "",
);
writeFileSync(target, L.join("\n"));
console.log(`Wrote ${target}.`);
